trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: '3.12'
  imageRepository: 'fastapi-app'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

stages:

- stage: Build
  displayName: Build & Test

  jobs:
  - job: CI

    steps:
    - checkout: self

    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(pythonVersion)

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: Install Dependencies

    - script: |
        pytest
      displayName: Run Tests


- stage: Docker
  displayName: Build & Push Image

  dependsOn: Build

  jobs:
  - job: Docker

    steps:

    - task: Docker@2
      displayName: Login to Azure Container Registry
      inputs:
        command: login
        containerRegistry: AzureACR

    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          latest
          $(tag)

    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: AzureACR
        tags: |
          latest
          $(tag)